### ISSUE TITLE
需求汇集清单

### ISSUE THREAD

**Issue by Atomx3** [tane-rs/meat_atlas#1]
2019.8.15- 11.23
决定不再使用paper的报告，而是用更短小的summary。
接收来自bright green ，NYU 教授的review 邮件，反馈在摘要的comments中，详见：google docs, Goodfood Meat Atlas Summary 肉食数据地图摘要

2019.3.18-8.15
参考 Goodfood Report- Work Summary 中国肉食地图- 工作总结
https://drive.google.com/

**Comment by Atomx3** [comment]
2019.11.27- 12.31
接收来自Weili的项目修改需求，反馈在摘要的comments中，详见：
google docs, Goodfood Meat Atlas Summary 肉食数据地图摘要

将原文档summary 更新版本，最终交付的文档为：
Meat Atlas Reporter Slides
Meat Atlas Overview Docs

图1：中国大陆主要动物产品的历史产量 （ resolved）
需求：人口，GDP，水产生变化迅速

图8-9：中国大陆动物食品消费总量和人均消费量的世界排名
需求：转化成占比（环形图），不需要排名。做中国和世界、美国、OECD和亚洲的占比的对比

图3：猪的个体生产效率出现较强的波动甚至下降，这可能和繁育配种及管理不当有关
需求：对比柱状图

图11：中国大陆的人均动物产品消费量的城乡地区比较
上面一张图可以按消费量的高低排序吗？
城乡有在人均消费上有没有明显的差距吗？

**Comment by tane-rs** [comment]
> 2019.8.15- 11.23
> 决定不再使用paper的报告，而是用更短小的summary。
> 接收来自bright green ，NYU 教授的review 邮件，反馈在摘要的comments中，详见：google docs, Goodfood Meat Atlas Summary 肉食数据地图摘要
> 
> 2019.3.18-8.15
> 参考 Goodfood Report- Work Summary 中国肉食地图- 工作总结
> https://drive.google.com/
